const mt = @import("meteorite_graph");

// Copy these stubs into native/src/handlers.zig or use `moon meteorite sync` later.

pub fn plain(c: mt.ctx.plain) !void {
    // <meteorite:generated-stub>
    // This handler was generated by Meteorite.
    // Replace the body before shipping release-static.
    _ = c;
    return c.text(501, "handler `plain` is not implemented");
    // </meteorite:generated-stub>
}

pub fn plain_static(c: mt.ctx.plain_static) !void {
    // <meteorite:generated-stub>
    // This handler was generated by Meteorite.
    // Replace the body before shipping release-static.
    _ = c;
    return c.text(501, "handler `plain_static` is not implemented");
    // </meteorite:generated-stub>
}

pub fn hybrid_zig(c: mt.ctx.hybrid_zig) !void {
    // <meteorite:generated-stub>
    // This handler was generated by Meteorite.
    // Replace the body before shipping release-static.
    _ = c;
    return c.text(501, "handler `hybrid_zig` is not implemented");
    // </meteorite:generated-stub>
}

pub fn bench_meta(c: mt.ctx.bench_meta) !void {
    // <meteorite:generated-stub>
    // This handler was generated by Meteorite.
    // Replace the body before shipping release-static.
    _ = c;
    return c.text(501, "handler `bench_meta` is not implemented");
    // </meteorite:generated-stub>
}

pub fn bench_raw(c: mt.ctx.bench_raw) !void {
    // <meteorite:generated-stub>
    // This handler was generated by Meteorite.
    // Replace the body before shipping release-static.
    _ = c;
    return c.text(501, "handler `bench_raw` is not implemented");
    // </meteorite:generated-stub>
}

pub fn bench_counters(c: mt.ctx.bench_counters) !void {
    // <meteorite:generated-stub>
    // This handler was generated by Meteorite.
    // Replace the body before shipping release-static.
    _ = c;
    return c.text(501, "handler `bench_counters` is not implemented");
    // </meteorite:generated-stub>
}

pub fn health(c: mt.ctx.health) !void {
    // <meteorite:generated-stub>
    // This handler was generated by Meteorite.
    // Replace the body before shipping release-static.
    _ = c;
    return c.text(501, "handler `health` is not implemented");
    // </meteorite:generated-stub>
}

pub fn get_user(c: mt.ctx.get_user) !void {
    // <meteorite:generated-stub>
    // This handler was generated by Meteorite.
    // Replace the body before shipping release-static.
    _ = c.params.id;
    return c.text(501, "handler `get_user` is not implemented");
    // </meteorite:generated-stub>
}

pub fn put_user(c: mt.ctx.put_user) !void {
    // <meteorite:generated-stub>
    // This handler was generated by Meteorite.
    // Replace the body before shipping release-static.
    _ = c.params.id;
    return c.text(501, "handler `put_user` is not implemented");
    // </meteorite:generated-stub>
}

pub fn patch_user(c: mt.ctx.patch_user) !void {
    // <meteorite:generated-stub>
    // This handler was generated by Meteorite.
    // Replace the body before shipping release-static.
    _ = c.params.id;
    return c.text(501, "handler `patch_user` is not implemented");
    // </meteorite:generated-stub>
}

pub fn delete_user(c: mt.ctx.delete_user) !void {
    // <meteorite:generated-stub>
    // This handler was generated by Meteorite.
    // Replace the body before shipping release-static.
    _ = c.params.id;
    return c.text(501, "handler `delete_user` is not implemented");
    // </meteorite:generated-stub>
}

pub fn echo(c: mt.ctx.echo) !void {
    // <meteorite:generated-stub>
    // This handler was generated by Meteorite.
    // Replace the body before shipping release-static.
    _ = c;
    return c.text(501, "handler `echo` is not implemented");
    // </meteorite:generated-stub>
}

pub fn get_device(c: mt.ctx.get_device) !void {
    // <meteorite:generated-stub>
    // This handler was generated by Meteorite.
    // Replace the body before shipping release-static.
    _ = c.params.device_id;
    return c.text(501, "handler `get_device` is not implemented");
    // </meteorite:generated-stub>
}

pub fn file(c: mt.ctx.file) !void {
    // <meteorite:generated-stub>
    // This handler was generated by Meteorite.
    // Replace the body before shipping release-static.
    _ = c.params.name;
    return c.text(501, "handler `file` is not implemented");
    // </meteorite:generated-stub>
}

pub fn slug(c: mt.ctx.slug) !void {
    // <meteorite:generated-stub>
    // This handler was generated by Meteorite.
    // Replace the body before shipping release-static.
    _ = c.params.slug;
    return c.text(501, "handler `slug` is not implemented");
    // </meteorite:generated-stub>
}

pub fn uuid(c: mt.ctx.uuid) !void {
    // <meteorite:generated-stub>
    // This handler was generated by Meteorite.
    // Replace the body before shipping release-static.
    _ = c.params.id;
    return c.text(501, "handler `uuid` is not implemented");
    // </meteorite:generated-stub>
}

pub fn hex(c: mt.ctx.hex) !void {
    // <meteorite:generated-stub>
    // This handler was generated by Meteorite.
    // Replace the body before shipping release-static.
    _ = c.params.digest;
    return c.text(501, "handler `hex` is not implemented");
    // </meteorite:generated-stub>
}

pub fn email(c: mt.ctx.email) !void {
    // <meteorite:generated-stub>
    // This handler was generated by Meteorite.
    // Replace the body before shipping release-static.
    _ = c.params.email;
    return c.text(501, "handler `email` is not implemented");
    // </meteorite:generated-stub>
}

pub fn token(c: mt.ctx.token) !void {
    // <meteorite:generated-stub>
    // This handler was generated by Meteorite.
    // Replace the body before shipping release-static.
    _ = c.params.token;
    return c.text(501, "handler `token` is not implemented");
    // </meteorite:generated-stub>
}

pub fn search(c: mt.ctx.search) !void {
    // <meteorite:generated-stub>
    // This handler was generated by Meteorite.
    // Replace the body before shipping release-static.
    _ = c.query.exact;
    _ = c.query.page;
    _ = c.query.q;
    return c.text(501, "handler `search` is not implemented");
    // </meteorite:generated-stub>
}

pub fn hybrid_inline(c: mt.ctx.hybrid_inline) !void {
    // <meteorite:generated-stub>
    // This handler was generated by Meteorite.
    // Replace the body before shipping release-static.
    _ = c;
    return c.text(501, "handler `hybrid_inline` is not implemented");
    // </meteorite:generated-stub>
}

pub fn bench_hybrid_inline(c: mt.ctx.bench_hybrid_inline) !void {
    // <meteorite:generated-stub>
    // This handler was generated by Meteorite.
    // Replace the body before shipping release-static.
    _ = c;
    return c.text(501, "handler `bench_hybrid_inline` is not implemented");
    // </meteorite:generated-stub>
}

pub fn bench_hybrid_inline_text_literal(c: mt.ctx.bench_hybrid_inline_text_literal) !void {
    // <meteorite:generated-stub>
    // This handler was generated by Meteorite.
    // Replace the body before shipping release-static.
    _ = c;
    return c.text(501, "handler `bench_hybrid_inline_text_literal` is not implemented");
    // </meteorite:generated-stub>
}

pub fn hybrid_inline_params(c: mt.ctx.hybrid_inline_params) !void {
    // <meteorite:generated-stub>
    // This handler was generated by Meteorite.
    // Replace the body before shipping release-static.
    _ = c.params.id;
    return c.text(501, "handler `hybrid_inline_params` is not implemented");
    // </meteorite:generated-stub>
}

pub fn hybrid_inline_echo(c: mt.ctx.hybrid_inline_echo) !void {
    // <meteorite:generated-stub>
    // This handler was generated by Meteorite.
    // Replace the body before shipping release-static.
    _ = c;
    return c.text(501, "handler `hybrid_inline_echo` is not implemented");
    // </meteorite:generated-stub>
}

pub fn bench_unavailable_state(c: mt.ctx.bench_unavailable_state) !void {
    // <meteorite:generated-stub>
    // This handler was generated by Meteorite.
    // Replace the body before shipping release-static.
    _ = c;
    return c.text(501, "handler `bench_unavailable_state` is not implemented");
    // </meteorite:generated-stub>
}

pub fn bench_unavailable_global(c: mt.ctx.bench_unavailable_global) !void {
    // <meteorite:generated-stub>
    // This handler was generated by Meteorite.
    // Replace the body before shipping release-static.
    _ = c;
    return c.text(501, "handler `bench_unavailable_global` is not implemented");
    // </meteorite:generated-stub>
}

pub fn bench_unavailable_leak(c: mt.ctx.bench_unavailable_leak) !void {
    // <meteorite:generated-stub>
    // This handler was generated by Meteorite.
    // Replace the body before shipping release-static.
    _ = c;
    return c.text(501, "handler `bench_unavailable_leak` is not implemented");
    // </meteorite:generated-stub>
}

pub fn bench_unavailable_shared(c: mt.ctx.bench_unavailable_shared) !void {
    // <meteorite:generated-stub>
    // This handler was generated by Meteorite.
    // Replace the body before shipping release-static.
    _ = c;
    return c.text(501, "handler `bench_unavailable_shared` is not implemented");
    // </meteorite:generated-stub>
}

pub fn bench_unavailable_worker(c: mt.ctx.bench_unavailable_worker) !void {
    // <meteorite:generated-stub>
    // This handler was generated by Meteorite.
    // Replace the body before shipping release-static.
    _ = c;
    return c.text(501, "handler `bench_unavailable_worker` is not implemented");
    // </meteorite:generated-stub>
}

pub fn bench_unavailable_require(c: mt.ctx.bench_unavailable_require) !void {
    // <meteorite:generated-stub>
    // This handler was generated by Meteorite.
    // Replace the body before shipping release-static.
    _ = c;
    return c.text(501, "handler `bench_unavailable_require` is not implemented");
    // </meteorite:generated-stub>
}
