const mt = @import("meteorite_graph");

// Copy these stubs into zig/handlers.zig or use `moon meteorite sync` later.

pub fn health(c: mt.ctx.health) !void {
    // <meteorite:generated-stub>
    // This handler was generated by Meteorite.
    // Replace the body before shipping release-static.
    _ = c;
    return c.text(501, "handler `health` is not implemented");
    // </meteorite:generated-stub>
}
