const mt = @import("meteorite_graph");

// Copy these stubs into zig/handlers.zig or use `moon meteorite sync` later.

pub fn health(c: mt.ctx.health) !void {
    // <meteorite:generated-stub>
    // This handler was generated by Meteorite.
    // Replace the body before shipping release-static.
    _ = c;
    return c.text(501, "handler `health` is not implemented");
    // </meteorite:generated-stub>
}

pub fn get_user(c: mt.ctx.get_user) !void {
    // <meteorite:generated-stub>
    // This handler was generated by Meteorite.
    // Replace the body before shipping release-static.
    _ = c.params.id;
    return c.text(501, "handler `get_user` is not implemented");
    // </meteorite:generated-stub>
}

pub fn put_user(c: mt.ctx.put_user) !void {
    // <meteorite:generated-stub>
    // This handler was generated by Meteorite.
    // Replace the body before shipping release-static.
    _ = c.params.id;
    return c.text(501, "handler `put_user` is not implemented");
    // </meteorite:generated-stub>
}

pub fn patch_user(c: mt.ctx.patch_user) !void {
    // <meteorite:generated-stub>
    // This handler was generated by Meteorite.
    // Replace the body before shipping release-static.
    _ = c.params.id;
    return c.text(501, "handler `patch_user` is not implemented");
    // </meteorite:generated-stub>
}

pub fn delete_user(c: mt.ctx.delete_user) !void {
    // <meteorite:generated-stub>
    // This handler was generated by Meteorite.
    // Replace the body before shipping release-static.
    _ = c.params.id;
    return c.text(501, "handler `delete_user` is not implemented");
    // </meteorite:generated-stub>
}

pub fn echo(c: mt.ctx.echo) !void {
    // <meteorite:generated-stub>
    // This handler was generated by Meteorite.
    // Replace the body before shipping release-static.
    _ = c;
    return c.text(501, "handler `echo` is not implemented");
    // </meteorite:generated-stub>
}

pub fn get_device(c: mt.ctx.get_device) !void {
    // <meteorite:generated-stub>
    // This handler was generated by Meteorite.
    // Replace the body before shipping release-static.
    _ = c.params.device_id;
    return c.text(501, "handler `get_device` is not implemented");
    // </meteorite:generated-stub>
}

pub fn file(c: mt.ctx.file) !void {
    // <meteorite:generated-stub>
    // This handler was generated by Meteorite.
    // Replace the body before shipping release-static.
    _ = c.params.name;
    return c.text(501, "handler `file` is not implemented");
    // </meteorite:generated-stub>
}

pub fn slug(c: mt.ctx.slug) !void {
    // <meteorite:generated-stub>
    // This handler was generated by Meteorite.
    // Replace the body before shipping release-static.
    _ = c.params.slug;
    return c.text(501, "handler `slug` is not implemented");
    // </meteorite:generated-stub>
}

pub fn uuid(c: mt.ctx.uuid) !void {
    // <meteorite:generated-stub>
    // This handler was generated by Meteorite.
    // Replace the body before shipping release-static.
    _ = c.params.id;
    return c.text(501, "handler `uuid` is not implemented");
    // </meteorite:generated-stub>
}

pub fn hex(c: mt.ctx.hex) !void {
    // <meteorite:generated-stub>
    // This handler was generated by Meteorite.
    // Replace the body before shipping release-static.
    _ = c.params.digest;
    return c.text(501, "handler `hex` is not implemented");
    // </meteorite:generated-stub>
}

pub fn email(c: mt.ctx.email) !void {
    // <meteorite:generated-stub>
    // This handler was generated by Meteorite.
    // Replace the body before shipping release-static.
    _ = c.params.email;
    return c.text(501, "handler `email` is not implemented");
    // </meteorite:generated-stub>
}

pub fn token(c: mt.ctx.token) !void {
    // <meteorite:generated-stub>
    // This handler was generated by Meteorite.
    // Replace the body before shipping release-static.
    _ = c.params.token;
    return c.text(501, "handler `token` is not implemented");
    // </meteorite:generated-stub>
}

pub fn search(c: mt.ctx.search) !void {
    // <meteorite:generated-stub>
    // This handler was generated by Meteorite.
    // Replace the body before shipping release-static.
    _ = c.query.exact;
    _ = c.query.page;
    _ = c.query.q;
    return c.text(501, "handler `search` is not implemented");
    // </meteorite:generated-stub>
}

pub fn hybrid_inline(c: mt.ctx.hybrid_inline) !void {
    // <meteorite:generated-stub>
    // This handler was generated by Meteorite.
    // Replace the body before shipping release-static.
    _ = c;
    return c.text(501, "handler `hybrid_inline` is not implemented");
    // </meteorite:generated-stub>
}
