local ballad = require("ballad")

return ballad.partiture(function(p)
	local moonstone = p:use(ballad.plugins.moonstone)

	local project = moonstone.project({ root = "." })
	local source_artifact = moonstone.registry.source_package(project, {
		name = project.registry_name or "moonstone/meteorite",
		version = project.version,
		kind = "bin",
		readme = "README.md",
		include = {
			"HMR_partiture.lua",
			"moonstone.toml",
			"moonstone.lock",
			"build.zig",
			"bin/**",
			"src/**",
			"zig/**",
			"scripts/**",
			"templates/**",
			"src/codegen/templates/**",
			"docs/**",
			"README.md",
		},
		exclude = {
			".meteorite/**",
			".moonstone/**",
			".ballad/**",
			".zig-cache/**",
			"zig-cache/**",
			"zig-out/**",
			"dist/**",
			"fixtures/**",
			".git/**",
		},
		materialize = {
			type = "command",
			command = "zig build install-server -- dist/server",
			collect = {
				bins = {
					{ name = "meteorite", path = "bin/meteorite" },
				},
				headers = {},
				lua_modules = {
					{ name = "meteorite.lua", path = "src/meteorite.lua" },
					{ name = "meteorite/core/route.lua", path = "src/core/route.lua" },
					{ name = "meteorite/core/contract.lua", path = "src/core/contract.lua" },
					{ name = "meteorite/core/plugin_contract.lua", path = "src/core/plugin_contract.lua" },
					{ name = "meteorite/core/hooks.lua", path = "src/core/hooks.lua" },
					{ name = "meteorite/core/plugins/cache.lua", path = "src/core/plugins/cache.lua" },
					{ name = "meteorite/core/plugins/idempotency.lua", path = "src/core/plugins/idempotency.lua" },
					{ name = "meteorite/core/schema.lua", path = "src/core/schema.lua" },
					{ name = "meteorite/core/profile.lua", path = "src/core/profile.lua" },
					{ name = "meteorite/core/patterns.lua", path = "src/core/patterns.lua" },
					{ name = "meteorite/core/handler_factories.lua", path = "src/core/handler_factories.lua" },
					{ name = "meteorite/core/site.lua", path = "src/core/site.lua" },
					{ name = "meteorite/codegen/emitter.lua", path = "src/codegen/emitter.lua" },
					{ name = "meteorite/codegen/lifter.lua", path = "src/codegen/lifter.lua" },
					{ name = "meteorite/codegen/static.lua", path = "src/codegen/static.lua" },
					{ name = "meteorite/codegen/partitions.lua", path = "src/codegen/partitions.lua" },
					{ name = "meteorite/codegen/zon.lua", path = "src/codegen/zon.lua" },
					{ name = "meteorite/codegen/helpers.lua", path = "src/codegen/helpers.lua" },
					{ name = "meteorite/codegen/report.lua", path = "src/codegen/report.lua" },
					{ name = "meteorite/codegen/handler_sync.lua", path = "src/codegen/handler_sync.lua" },
					{ name = "meteorite/codegen/graph_emit.lua", path = "src/codegen/graph_emit.lua" },
					{ name = "meteorite/utils/fs.lua", path = "src/utils/fs.lua" },
					{ name = "meteorite/cli/help_text.lua", path = "src/cli/help_text.lua" },
					{ name = "meteorite/cli/templates.lua", path = "src/cli/templates.lua" },
					{ name = "meteorite/codegen/template.lua", path = "src/codegen/template.lua" },
					{
						name = "meteorite/codegen/templates/route.zig.tpl",
						path = "src/codegen/templates/route.zig.tpl",
					},
					{
						name = "meteorite/codegen/templates/pattern.zig.tpl",
						path = "src/codegen/templates/pattern.zig.tpl",
					},
					{
						name = "meteorite/codegen/templates/build_report.txt.tpl",
						path = "src/codegen/templates/build_report.txt.tpl",
					},
					{ name = "meteorite/cli/main.lua", path = "src/cli/main.lua" },
					{ name = "meteorite/cli/dev.lua", path = "src/cli/dev.lua" },
					{ name = "meteorite/cli/hybrid.lua", path = "src/cli/hybrid.lua" },
					{ name = "meteorite/cli/http_client.lua", path = "src/cli/http_client.lua" },
					{ name = "meteorite/utils/json.lua", path = "src/utils/json.lua" },
					{ name = "meteorite/ballad.lua", path = "src/meteorite/ballad.lua" },
					{ name = "docs/examples.md", path = "docs/examples.md" },
					{ name = "build.zig", path = "build.zig" },
					{ name = "zig/main.zig", path = "zig/main.zig" },
					{ name = "zig/meteorite.zig", path = "zig/meteorite.zig" },
					{ name = "zig/bridge.zig", path = "zig/bridge.zig" },
					{ name = "zig/pattern.zig", path = "zig/pattern.zig" },
					{ name = "zig/empty_handlers.zig", path = "zig/empty_handlers.zig" },
					{ name = "zig/empty_validators.zig", path = "zig/empty_validators.zig" },
					{ name = "zig/backends/protocol.zig", path = "zig/backends/protocol.zig" },
					{ name = "zig/server/signals.zig", path = "zig/server/signals.zig" },
					{ name = "zig/server/http_date.zig", path = "zig/server/http_date.zig" },
					{ name = "zig/server/validators.zig", path = "zig/server/validators.zig" },
					{ name = "zig/server/static_files.zig", path = "zig/server/static_files.zig" },
					{ name = "zig/server/request_limits.zig", path = "zig/server/request_limits.zig" },
					{ name = "zig/bridge/c_imports.zig", path = "zig/bridge/c_imports.zig" },
					{ name = "zig/bridge/lua_stats.zig", path = "zig/bridge/lua_stats.zig" },
					{ name = "zig/bridge/lua_vtable.zig", path = "zig/bridge/lua_vtable.zig" },
					{ name = "zig/bridge/lua_json.zig", path = "zig/bridge/lua_json.zig" },
					{ name = "zig/bridge/lua_http.zig", path = "zig/bridge/lua_http.zig" },
					{ name = "zig/bridge/lua_bindings.zig", path = "zig/bridge/lua_bindings.zig" },
					{ name = "zig/backends/std_http.zig", path = "zig/backends/std_http.zig" },
					{ name = "zig/backends/fast_http.zig", path = "zig/backends/fast_http.zig" },
					{ name = "ballad/init.lua", path = "src/ballad/init.lua" },
					{ name = "ballad/release_assets.lua", path = "src/ballad/release_assets.lua" },
					{ name = "ballad/release_contract.lua", path = "src/ballad/release_contract.lua" },
					{ name = "ballad/release_manifest.lua", path = "src/ballad/release_manifest.lua" },
					{ name = "ballad/release_tasks.lua", path = "src/ballad/release_tasks.lua" },
					{ name = "templates/project/.luarc.json", path = "templates/project/.luarc.json" },
					{ name = "templates/project/README.md", path = "templates/project/README.md" },
					{ name = "templates/project/src/main.lua", path = "templates/project/src/main.lua" },
					{ name = "templates/project/src/app.lua", path = "templates/project/src/app.lua" },
					{
						name = "templates/project/zig/handlers.zig",
						path = "templates/project/zig/handlers.zig",
					},
					{
						name = "templates/project/zig/validators.zig",
						path = "templates/project/zig/validators.zig",
					},
					{ name = "templates/static/.luarc.json", path = "templates/static/.luarc.json" },
					{ name = "templates/static/README.md", path = "templates/static/README.md" },
					{ name = "templates/static/src/main.lua", path = "templates/static/src/main.lua" },
					{ name = "templates/static/src/app.lua", path = "templates/static/src/app.lua" },
					{
						name = "templates/static/zig/handlers/root.zig",
						path = "templates/static/zig/handlers/root.zig",
					},
					{
						name = "templates/static/zig/handlers/health.zig",
						path = "templates/static/zig/handlers/health.zig",
					},
					{ name = "templates/hybrid/.luarc.json", path = "templates/hybrid/.luarc.json" },
					{ name = "templates/hybrid/README.md", path = "templates/hybrid/README.md" },
					{ name = "templates/hybrid/src/main.lua", path = "templates/hybrid/src/main.lua" },
					{ name = "templates/hybrid/src/app.lua", path = "templates/hybrid/src/app.lua" },
					{
						name = "templates/hybrid/zig/handlers/zig.zig",
						path = "templates/hybrid/zig/handlers/zig.zig",
					},
				},
			},
		},
	})

	p.sink.artifact(source_artifact, { out = "dist/registry/meteorite" })
end)
