local ballad = require("ballad")
local common = require("partiture_common")

return ballad.partiture(function(p)
	local moonstone = p:use(ballad.plugins.moonstone)

	local project = moonstone.project({ root = "." })
	local source_artifact = moonstone.registry.source_package(project, {
		name = project.registry_name or "moonstone/meteorite",
		version = project.version,
		kind = "bin",
		include = {
			"Watch_partiture.lua",
			"partiture_common.lua",
			"build.zig",
			"bin/**",
			"src/**",
			"zig/**",
			"scripts/**",
			"templates/**",
			"src/codegen/templates/**",
			"docs/**",
			"README.md",
			"REGISTRY_README.md",
		},
		exclude = {
			".meteorite/**",
			".moonstone/**",
			".ballad/**",
			".zig-cache/**",
			"zig-cache/**",
			"zig-out/**",
			"dist/**",
			"fixtures/**",
			".git/**",
			"**/.moonstone",
			"**/.moonstone/**",
			"**/.meteorite",
			"**/.meteorite/**",
			"**/.ballad",
			"**/.ballad/**",
			"**/.DS_Store",
		},
		materialize = {
			type = "command",
			command = "true",
			collect = {
				bins = {
					{ name = "bin/meteorite", path = "bin/meteorite" },
				},
				headers = {},
				lua_modules = {
					{ name = "meteorite.lua", path = "src/meteorite.lua" },
					{ name = "meteorite/core/route.lua", path = "src/core/route.lua" },
					{ name = "meteorite/core/contract.lua", path = "src/core/contract.lua" },
					{ name = "meteorite/core/plugin_contract.lua", path = "src/core/plugin_contract.lua" },
					{ name = "meteorite/core/hooks.lua", path = "src/core/hooks.lua" },
					{ name = "meteorite/core/plugins/cache.lua", path = "src/core/plugins/cache.lua" },
					{ name = "meteorite/core/plugins/idempotency.lua", path = "src/core/plugins/idempotency.lua" },
					{ name = "meteorite/core/schema.lua", path = "src/core/schema.lua" },
					{ name = "meteorite/core/profile.lua", path = "src/core/profile.lua" },
					{ name = "meteorite/core/patterns.lua", path = "src/core/patterns.lua" },
					{ name = "meteorite/core/handler_factories.lua", path = "src/core/handler_factories.lua" },
					{ name = "meteorite/core/site.lua", path = "src/core/site.lua" },
					{ name = "meteorite/codegen/emitter.lua", path = "src/codegen/emitter.lua" },
					{ name = "meteorite/codegen/lifter.lua", path = "src/codegen/lifter.lua" },
					{ name = "meteorite/codegen/static.lua", path = "src/codegen/static.lua" },
					{ name = "meteorite/codegen/partitions.lua", path = "src/codegen/partitions.lua" },
					{ name = "meteorite/codegen/zon.lua", path = "src/codegen/zon.lua" },
					{ name = "meteorite/codegen/helpers.lua", path = "src/codegen/helpers.lua" },
					{ name = "meteorite/codegen/report.lua", path = "src/codegen/report.lua" },
					{ name = "meteorite/codegen/handler_sync.lua", path = "src/codegen/handler_sync.lua" },
					{ name = "meteorite/codegen/graph_emit.lua", path = "src/codegen/graph_emit.lua" },
					{ name = "meteorite/utils/fs.lua", path = "src/utils/fs.lua" },
					{ name = "meteorite/cli/help_text.lua", path = "src/cli/help_text.lua" },
					{ name = "meteorite/cli/templates.lua", path = "src/cli/templates.lua" },
					{ name = "meteorite/cli/app_loader.lua", path = "src/cli/app_loader.lua" },
					{ name = "meteorite/cli/build.lua", path = "src/cli/build.lua" },
					{ name = "meteorite/cli/check.lua", path = "src/cli/check.lua" },
					{ name = "meteorite/cli/client.lua", path = "src/cli/client.lua" },
					{ name = "meteorite/cli/deps.lua", path = "src/cli/deps.lua" },
					{ name = "meteorite/cli/dev_command.lua", path = "src/cli/dev_command.lua" },
					{ name = "meteorite/cli/doctor.lua", path = "src/cli/doctor.lua" },
					{ name = "meteorite/cli/fs.lua", path = "src/cli/fs.lua" },
					{ name = "meteorite/cli/graph.lua", path = "src/cli/graph.lua" },
					{ name = "meteorite/cli/init.lua", path = "src/cli/init.lua" },
					{ name = "meteorite/cli/invoke_command.lua", path = "src/cli/invoke_command.lua" },
					{ name = "meteorite/cli/ipc.lua", path = "src/cli/ipc.lua" },
					{ name = "meteorite/cli/openapi.lua", path = "src/cli/openapi.lua" },
					{ name = "meteorite/cli/package_context.lua", path = "src/cli/package_context.lua" },
					{ name = "meteorite/cli/routes.lua", path = "src/cli/routes.lua" },
					{ name = "meteorite/build_request.lua", path = "src/meteorite/build_request.lua" },
					{ name = "meteorite/cli/shell.lua", path = "src/cli/shell.lua" },
					{ name = "meteorite/cli/sync.lua", path = "src/cli/sync.lua" },
					{ name = "meteorite/codegen/template.lua", path = "src/codegen/template.lua" },
					{ name = "meteorite/codegen/build_report.lua", path = "src/codegen/build_report.lua" },
					{ name = "meteorite/codegen/graph_bindings.lua", path = "src/codegen/graph_bindings.lua" },
					{ name = "meteorite/codegen/graph_capabilities.lua", path = "src/codegen/graph_capabilities.lua" },
					{ name = "meteorite/codegen/graph_patterns.lua", path = "src/codegen/graph_patterns.lua" },
					{ name = "meteorite/codegen/graph_prepare.lua", path = "src/codegen/graph_prepare.lua" },
					{ name = "meteorite/codegen/graph_routes.lua", path = "src/codegen/graph_routes.lua" },
					{ name = "meteorite/codegen/graph_zig.lua", path = "src/codegen/graph_zig.lua" },
					{ name = "meteorite/codegen/lua_client.lua", path = "src/codegen/lua_client.lua" },
					{ name = "meteorite/codegen/luals_aids.lua", path = "src/codegen/luals_aids.lua" },
					{ name = "meteorite/codegen/openapi.lua", path = "src/codegen/openapi.lua" },
					{ name = "meteorite/codegen/openapi_plan.lua", path = "src/codegen/openapi_plan.lua" },
					{ name = "meteorite/codegen/route_zon.lua", path = "src/codegen/route_zon.lua" },
					{ name = "meteorite/codegen/schema_doc.lua", path = "src/codegen/schema_doc.lua" },
					{ name = "meteorite/codegen/schema_ir.lua", path = "src/codegen/schema_ir.lua" },
					{ name = "meteorite/codegen/swagger_ui.lua", path = "src/codegen/swagger_ui.lua" },
					{ name = "meteorite/core/app.lua", path = "src/core/app.lua" },
					{ name = "meteorite/core/handler_exports.lua", path = "src/core/handler_exports.lua" },
					{ name = "meteorite/core/schema_exports.lua", path = "src/core/schema_exports.lua" },
					{ name = "meteorite/core/template.lua", path = "src/core/template.lua" },
					{ name = "meteorite/core/utility_exports.lua", path = "src/core/utility_exports.lua" },
					{
						name = "meteorite/codegen/templates/route.zig.tpl",
						path = "src/codegen/templates/route.zig.tpl",
					},
					{
						name = "meteorite/codegen/templates/pattern.zig.tpl",
						path = "src/codegen/templates/pattern.zig.tpl",
					},
					{
						name = "meteorite/codegen/templates/build_report.txt.tpl",
						path = "src/codegen/templates/build_report.txt.tpl",
					},
					{ name = "meteorite/cli/main.lua", path = "src/cli/main.lua" },
					{ name = "meteorite/cli/dev.lua", path = "src/cli/dev.lua" },
					{ name = "meteorite/cli/hybrid.lua", path = "src/cli/hybrid.lua" },
					{ name = "meteorite/cli/http_client.lua", path = "src/cli/http_client.lua" },
					{ name = "meteorite/utils/json.lua", path = "src/utils/json.lua" },
					{ name = "meteorite/ballad.lua", path = "src/ballad_plugin/meteorite/ballad.lua" },
					{ name = "docs/examples.md", path = "docs/examples.md" },
					{ name = "build.zig", path = "build.zig" },
					{ name = "zig/main.zig", path = "zig/main.zig" },
					{ name = "zig/meteorite.zig", path = "zig/meteorite.zig" },
					{ name = "zig/bridge.zig", path = "zig/bridge.zig" },
					{ name = "zig/pattern.zig", path = "zig/pattern.zig" },
					{ name = "zig/empty_handlers.zig", path = "zig/empty_handlers.zig" },
					{ name = "zig/empty_validators.zig", path = "zig/empty_validators.zig" },
					{ name = "zig/backends/protocol.zig", path = "zig/backends/protocol.zig" },
					{ name = "zig/server/signals.zig", path = "zig/server/signals.zig" },
					{ name = "zig/server/http_date.zig", path = "zig/server/http_date.zig" },
					{ name = "zig/server/validators.zig", path = "zig/server/validators.zig" },
					{ name = "zig/server/static_files.zig", path = "zig/server/static_files.zig" },
					{ name = "zig/server/request_limits.zig", path = "zig/server/request_limits.zig" },
					{ name = "zig/bridge/c_imports.zig", path = "zig/bridge/c_imports.zig" },
					{ name = "zig/bridge/lua_stats.zig", path = "zig/bridge/lua_stats.zig" },
					{ name = "zig/bridge/lua_vtable.zig", path = "zig/bridge/lua_vtable.zig" },
					{ name = "zig/bridge/lua_json.zig", path = "zig/bridge/lua_json.zig" },
					{ name = "zig/bridge/lua_http.zig", path = "zig/bridge/lua_http.zig" },
					{ name = "zig/bridge/lua_bindings.zig", path = "zig/bridge/lua_bindings.zig" },
					{ name = "zig/backends/std_http.zig", path = "zig/backends/std_http.zig" },
					{ name = "zig/backends/fast_http.zig", path = "zig/backends/fast_http.zig" },
					{ name = "ballad/init.lua", path = "src/ballad/init.lua" },
					{ name = "ballad/release_assets.lua", path = "src/ballad/release_assets.lua" },
					{ name = "ballad/release_contract.lua", path = "src/ballad/release_contract.lua" },
					{ name = "ballad/release_manifest.lua", path = "src/ballad/release_manifest.lua" },
					{ name = "ballad/release_tasks.lua", path = "src/ballad/release_tasks.lua" },
					{ name = "templates/project/.luarc.json", path = "templates/project/.luarc.json" },
					{ name = "templates/project/README.md", path = "templates/project/README.md" },
					{ name = "templates/project/src/main.lua", path = "templates/project/src/main.lua" },
					{ name = "templates/project/src/app.lua", path = "templates/project/src/app.lua" },
					{
						name = "templates/project/zig/handlers.zig",
						path = "templates/project/zig/handlers.zig",
					},
					{
						name = "templates/project/zig/validators.zig",
						path = "templates/project/zig/validators.zig",
					},
					{ name = "templates/static/.luarc.json", path = "templates/static/.luarc.json" },
					{ name = "templates/static/README.md", path = "templates/static/README.md" },
					{ name = "templates/static/src/main.lua", path = "templates/static/src/main.lua" },
					{ name = "templates/static/src/app.lua", path = "templates/static/src/app.lua" },
					{
						name = "templates/static/zig/handlers/root.zig",
						path = "templates/static/zig/handlers/root.zig",
					},
					{
						name = "templates/static/zig/handlers/health.zig",
						path = "templates/static/zig/handlers/health.zig",
					},
					{ name = "templates/hybrid/.luarc.json", path = "templates/hybrid/.luarc.json" },
					{ name = "templates/hybrid/README.md", path = "templates/hybrid/README.md" },
					{ name = "templates/hybrid/src/main.lua", path = "templates/hybrid/src/main.lua" },
					{ name = "templates/hybrid/src/app.lua", path = "templates/hybrid/src/app.lua" },
					{
						name = "templates/hybrid/zig/handlers/zig.zig",
						path = "templates/hybrid/zig/handlers/zig.zig",
					},
				},
			},
		},
	})

	p.sink.artifact(source_artifact, { out = "dist/registry/meteorite" })
end)
