const std = @import("std");

pub fn Info(comptime backend: anytype, comptime lua_runtime: anytype, comptime build_info: anytype) type {
    return struct {
        pub fn countersJson(allocator: std.mem.Allocator) ![]const u8 {
            const c = backend.snapshotCounters();
            const lua = lua_runtime.snapshotStats();
            const prefix = try std.fmt.allocPrint(allocator, "{{\"backend\":\"{s}\",\"connection_strategy\":\"{s}\",\"bounded\":{},\"active_connections\":{d},\"open_connections_current\":{d},\"inflight_current\":{d},\"inflight_requests_current\":{d},\"inflight_max\":{d},\"inflight_requests_max\":{d},\"open_connections_max\":{d},\"total_connections\":{d},\"accepted_connections\":{d},\"accepted_total\":{d},\"completed_total\":{d},\"threads_spawned\":{d},\"requests_served\":{d},\"requests_per_connection\":{d},\"keepalive_reuse_count\":{d},\"connection_close_count\":{d},\"bytes_read\":{d},\"bytes_written\":{d},\"connection_errors\":{d},\"malformed_frames\":{d},\"oversized_frames\":{d},\"protocol_errors\":{d},\"unauthorized_peers\":{d},\"early_closes\":{d}", .{ backend.name, backend.connection_strategy, backend.bounded, c.active_connections, c.active_connections, c.inflight_current, c.inflight_current, c.inflight_max, c.inflight_max, c.max_active_connections, c.total_connections, c.accepted_connections, c.accepted_total, c.completed_total, c.threads_spawned, c.requests_served, c.requests_per_connection, c.keepalive_reuse_count, c.connection_close_count, c.bytes_read, c.bytes_written, c.connection_errors, c.malformed_frames, c.oversized_frames, c.protocol_errors, c.unauthorized_peers, c.early_closes });
            defer allocator.free(prefix);
            const pressure = try std.fmt.allocPrint(allocator, ",\"max_active_connections\":{d},\"queue_depth\":{d},\"queue_depth_current\":{d},\"max_queue_depth\":{d},\"queue_depth_max\":{d},\"worker_queue_depth_max\":{d},\"budget_capacity\":{d},\"budget_rejections_total\":{d},\"backpressure_total\":{d},\"dropped_connections\":{d}", .{ c.max_active_connections, c.queue_depth, c.queue_depth, c.max_queue_depth, c.max_queue_depth, c.worker_queue_depth_max, c.budget_capacity, c.budget_rejections_total, c.backpressure_total, c.dropped_connections });
            defer allocator.free(pressure);
            const suffix = try std.fmt.allocPrint(allocator, ",\"lua_states_created\":{d},\"lua_handler_refs_loaded\":{d},\"lua_handler_calls\":{d},\"lua_errors\":{d},\"lua_state_reuse_hits\":{d},\"lua_state_reuse_misses\":{d},\"per_thread_state_count\":{d}}}", .{ lua.lua_states_created, lua.lua_handler_refs_loaded, lua.lua_handler_calls, lua.lua_errors, lua.lua_state_reuse_hits, lua.lua_state_reuse_misses, lua.per_thread_state_count });
            defer allocator.free(suffix);
            return std.mem.concat(allocator, u8, &.{ prefix, pressure, suffix });
        }
        
        pub fn metaJson(allocator: std.mem.Allocator) ![]const u8 {
            const c = backend.snapshotCounters();
            const lua = lua_runtime.snapshotStats();
            const prefix = try std.fmt.allocPrint(allocator, "{{\"meteorite_mode\":\"{s}\",\"zig_optimize\":\"{s}\",\"target\":\"{s}\",\"backend\":\"{s}\",\"transport\":\"{s}\",\"protocol\":\"{s}\",\"capabilities\":{{\"http_headers\":{},\"cookies\":{},\"cors\":{},\"redirects\":{},\"ipc_metadata\":{},\"peer_credentials\":{},\"static_files\":{}}},\"connection_strategy\":\"{s}\",\"backend_strategy\":\"{s}\",\"worker_strategy\":\"{s}\",\"bounded\":{},\"fast_http_workers\":{d},\"fast_http_queue\":{d},\"router_dispatch\":\"{s}\",\"worker_count\":{d},\"lua_runtime\":{},\"hybrid_profile\":\"{s}\",\"lua_state_strategy\":\"{s}\",\"lua_handler_ref_strategy\":\"{s}\",\"capability_store_strategy\":\"{s}\",\"require_cache_strategy\":\"{s}\"", .{ build_info.meteorite_mode, build_info.zig_optimize, build_info.target, backend.name, build_info.transport, build_info.protocol, build_info.capability_http_headers, build_info.capability_cookies, build_info.capability_cors, build_info.capability_redirects, build_info.capability_ipc_metadata, build_info.capability_peer_credentials, build_info.capability_static_files, backend.connection_strategy, backend.connection_strategy, backend.connection_strategy, backend.bounded, build_info.fast_http_workers, build_info.fast_http_queue, build_info.router_dispatch, c.threads_spawned, build_info.lua_runtime, build_info.hybrid_profile, lua_runtime.lua_state_strategy, lua_runtime.lua_handler_ref_strategy, lua_runtime.capability_store_strategy, lua_runtime.require_cache_strategy });
            defer allocator.free(prefix);
            const counters_suffix = try std.fmt.allocPrint(allocator, ",\"active_connections\":{d},\"open_connections_current\":{d},\"inflight_current\":{d},\"inflight_requests_current\":{d},\"inflight_max\":{d},\"inflight_requests_max\":{d},\"open_connections_max\":{d},\"total_connections\":{d},\"accepted_connections\":{d},\"accepted_total\":{d},\"completed_total\":{d},\"threads_spawned\":{d},\"requests_served\":{d},\"requests_per_connection\":{d},\"bytes_read\":{d},\"bytes_written\":{d},\"connection_errors\":{d},\"malformed_frames\":{d},\"oversized_frames\":{d},\"protocol_errors\":{d},\"unauthorized_peers\":{d},\"early_closes\":{d}", .{ c.active_connections, c.active_connections, c.inflight_current, c.inflight_current, c.inflight_max, c.inflight_max, c.max_active_connections, c.total_connections, c.accepted_connections, c.accepted_total, c.completed_total, c.threads_spawned, c.requests_served, c.requests_per_connection, c.bytes_read, c.bytes_written, c.connection_errors, c.malformed_frames, c.oversized_frames, c.protocol_errors, c.unauthorized_peers, c.early_closes });
            defer allocator.free(counters_suffix);
            const pressure_suffix = try std.fmt.allocPrint(allocator, ",\"max_active_connections\":{d},\"queue_depth\":{d},\"queue_depth_current\":{d},\"max_queue_depth\":{d},\"queue_depth_max\":{d},\"worker_queue_depth_max\":{d},\"budget_capacity\":{d},\"budget_rejections_total\":{d},\"backpressure_total\":{d},\"dropped_connections\":{d}", .{ c.max_active_connections, c.queue_depth, c.queue_depth, c.max_queue_depth, c.max_queue_depth, c.worker_queue_depth_max, c.budget_capacity, c.budget_rejections_total, c.backpressure_total, c.dropped_connections });
            defer allocator.free(pressure_suffix);
            const lua_suffix = try std.fmt.allocPrint(allocator, ",\"lua_states_created\":{d},\"lua_handler_refs_loaded\":{d},\"lua_handler_calls\":{d},\"lua_errors\":{d},\"lua_state_reuse_hits\":{d},\"lua_state_reuse_misses\":{d},\"per_thread_state_count\":{d}}}", .{ lua.lua_states_created, lua.lua_handler_refs_loaded, lua.lua_handler_calls, lua.lua_errors, lua.lua_state_reuse_hits, lua.lua_state_reuse_misses, lua.per_thread_state_count });
            defer allocator.free(lua_suffix);
            return std.mem.concat(allocator, u8, &.{ prefix, counters_suffix, pressure_suffix, lua_suffix });
        }
        
        pub fn buildInfoJson(allocator: std.mem.Allocator) ![]const u8 {
            return std.fmt.allocPrint(allocator, "{{\"format\":\"meteorite.info.v0\",\"meteorite_mode\":\"{s}\",\"zig_optimize\":\"{s}\",\"target\":\"{s}\",\"backend\":\"{s}\",\"transport\":\"{s}\",\"protocol\":\"{s}\",\"capabilities\":{{\"http_headers\":{},\"cookies\":{},\"cors\":{},\"redirects\":{},\"ipc_metadata\":{},\"peer_credentials\":{},\"static_files\":{}}},\"connection_strategy\":\"{s}\",\"backend_strategy\":\"{s}\",\"worker_strategy\":\"{s}\",\"bounded\":{},\"fast_http_workers\":{d},\"fast_http_queue\":{d},\"router_dispatch\":\"{s}\",\"lua_runtime\":{},\"hybrid_profile\":\"{s}\",\"lua_state_strategy\":\"{s}\",\"lua_handler_ref_strategy\":\"{s}\",\"capability_store_strategy\":\"{s}\",\"require_cache_strategy\":\"{s}\"}}", .{ build_info.meteorite_mode, build_info.zig_optimize, build_info.target, backend.name, build_info.transport, build_info.protocol, build_info.capability_http_headers, build_info.capability_cookies, build_info.capability_cors, build_info.capability_redirects, build_info.capability_ipc_metadata, build_info.capability_peer_credentials, build_info.capability_static_files, backend.connection_strategy, backend.connection_strategy, backend.connection_strategy, backend.bounded, build_info.fast_http_workers, build_info.fast_http_queue, build_info.router_dispatch, build_info.lua_runtime, build_info.hybrid_profile, lua_runtime.lua_state_strategy, lua_runtime.lua_handler_ref_strategy, lua_runtime.capability_store_strategy, lua_runtime.require_cache_strategy });
        }
        
    };
}
