[package]
name = "bench-pegasus"
version = "0.1.0"
kind = "bin"

[interpreter]
name = "luajit"
version = "2.1.1783773675"
abi = "5.1"

[[dependencies]]
name = "pegasus"
constraint = "rocks:pegasus@*"
role = "runtime"

[[dependencies]]
name = "luasocket"
constraint = "rocks:luasocket@*"
role = "runtime"

[[dependencies]]
name = "mimetypes"
constraint = "rocks:mimetypes@*"
role = "runtime"

[[dependencies]]
name = "luasql-sqlite3"
constraint = "^2.8.0-1"
resolver = "rocks"
role = "runtime"

[[dependencies]]
name = "etlua"
constraint = "rocks:etlua@*"
role = "runtime"

[[dependencies]]
name = "lua-cjson"
constraint = "rocks:lua-cjson@*"
role = "runtime"
